### ISSUE TITLE
Implement badgerauth's replication chore

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#164]
Depends on #163.

Ideally, the implementation should stack up on #122 and should follow the design of the replication algorithm laid out in the blueprint: [1](https://github.com/storj/gateway-mt/blob/3ef75f412a50118d9d910e1b372e126e6ffb7503/docs/blueprints/new-auth-database.md#replication-algorithm) & [2](https://github.com/storj/gateway-mt/blob/3ef75f412a50118d9d910e1b372e126e6ffb7503/docs/blueprints/new-auth-database.md#replicate-implementation).

Subtasks:

- [x] #177
- [x] #178
- [x] #179
- [x] #180
- [x] #182 
- [x] #181

**Comment by egonelbre** [comment]
- [ ] badgerauth: consolidate update logic
- [ ] badgerauth: fuzzing of update logic
- [ ] badgerauth: configuration of nodes
- [ ] badgerauth: setup of messaging
- [ ] badgerauth: tests of messaging

**Comment by amwolff** [comment]
Done ✅
